import{a as d,S as g,i}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const L="49649405-8aeb588384e19e05040c9b75c";d.defaults.baseURL="https://pixabay.com/api/";async function p(e,r){try{return(await d({params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:"15"}})).data}catch(t){return t.messege}}const b=document.querySelector(".gallery"),v=new g(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8});function f(e){const r=e.map(t=>`
    <li>
            <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}"/>
            </a>
            <div class="gallery-info">
            <p><span>Likes</span>${t.likes} </p>
            <p><span>Views</span>${t.views}</p>
            <p><span>Comments</span>${t.comments}</p>
            <p><span>Downloads</span>${t.downloads}</p>
            </div>
    </li>
    `).join("");b.insertAdjacentHTML("beforeend",r),v.refresh()}function w(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function y(){const e=document.querySelector(".loader");e&&e.classList.remove("visible")}function h(){const e=document.querySelector(".loader");e&&e.classList.add("visible")}function m(){const e=document.querySelector(".btn-load");e&&e.classList.remove("visible")}function l(){const e=document.querySelector(".btn-load");e&&e.classList.add("visible")}const u=document.querySelector("form"),q=document.querySelector(".btn-load");u.addEventListener("submit",M);q.addEventListener("click",R);let a,S="";async function M(e){e.preventDefault(),y();let r=u.elements["search-text"].value.trim();if(u.elements["search-text"].value){w();try{a=1;const t=await p(r,a),n=t.hits;if(n.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");f(n),n.length<t.totalHits?m():(l(),i.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){i.error({message:t.message,position:"topRight"})}finally{h()}}}async function R(){y(),l(),a++;try{const e=await p(S,a);let r=15*a;f(e.hits),r>=e.totalHits&&(l(),i.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const n=document.querySelector("li").getBoundingClientRect().height;window.scrollBy({left:0,top:n*2,behavior:"smooth"})}catch(e){i.error({message:e.message,position:"topRight"})}finally{h(),m()}}
//# sourceMappingURL=index.js.map
