import{a as g,S as L,i as c}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const b="49649405-8aeb588384e19e05040c9b75c",w="https://pixabay.com/api/";async function u(e,r){try{return(await g.get(w,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:"15"}})).data}catch(t){return t.messege}}const v=document.querySelector(".gallery"),S=new L(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8});function p(e){const r=e.map(t=>`
    <li>
            <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}"/>
            </a>
            <div class="gallery-info">
            <p><span>Likes</span>${t.likes} </p>
            <p><span>Views</span>${t.views}</p>
            <p><span>Comments</span>${t.comments}</p>
            <p><span>Downloads</span>${t.downloads}</p>
            </div>
    </li>
    `).join("");v.insertAdjacentHTML("beforeend",r),S.refresh()}function q(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function f(){const e=document.querySelector(".loader");e&&e.classList.remove("hidden")}function h(){const e=document.querySelector(".loader");e&&e.classList.add("hidden")}function y(){const e=document.querySelector(".btn-load");e&&e.classList.remove("hidden")}function l(){const e=document.querySelector(".btn-load");e&&e.classList.add("hidden")}const m=document.querySelector("form"),M=document.querySelector(".btn-load");m.addEventListener("submit",R);M.addEventListener("click",B);let n,i="";async function R(e){if(e.preventDefault(),i=m.elements["search-text"].value.trim(),!!i){f(),q();try{n=1;const r=await u(i,n),t=r.hits;if(t.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");p(t),t.length<r.totalHits?y():(l(),c.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){l(),c.error({message:r.message,position:"topRight"})}finally{h()}}}async function B(){f(),l(),n++;try{const e=await u(i,n);let r=15*n;p(e.hits),r>=e.totalHits&&(c.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l());const a=document.querySelector("li").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}catch(e){c.error({message:e.message,position:"topRight"})}finally{h(),y()}}
//# sourceMappingURL=index.js.map
