import{a as L,S as b,i as a}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const w="49649405-8aeb588384e19e05040c9b75c",S="https://pixabay.com/api/";async function p(e,r){try{return(await L.get(S,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:"15"}})).data}catch(t){return t.messege}}const v=document.querySelector(".gallery"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8});function f(e){const r=e.map(t=>`
    <li class = "gallery-item">
            <a href="${t.largeImageURL}">
            <img src="${t.webformatURL}" alt="${t.tags}"/>
            </a>
            <div class="gallery-info">
            <p><span>Likes</span>${t.likes} </p>
            <p><span>Views</span>${t.views}</p>
            <p><span>Comments</span>${t.comments}</p>
            <p><span>Downloads</span>${t.downloads}</p>
            </div>
    </li>
    `).join("");v.insertAdjacentHTML("beforeend",r),q.refresh()}function M(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function m(){const e=document.querySelector(".loader");e&&e.classList.remove("hidden")}function y(){const e=document.querySelector(".loader");e&&e.classList.add("hidden")}function h(){const e=document.querySelector(".btn-load");e&&e.classList.remove("hidden")}function i(){const e=document.querySelector(".btn-load");e&&e.classList.add("hidden")}const g=document.querySelector("form"),R=document.querySelector(".btn-load");g.addEventListener("submit",I);R.addEventListener("click",O);let l=1,n="",u=0;async function I(e){if(e.preventDefault(),n=g.elements["search-text"].value.trim(),!!n){m(),M();try{l=1;const r=await p(n,l),t=r.hits;if(u=r.totalHits,t.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");f(t),t.length<u?h():(i(),a.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){i(),a.error({message:r.message,position:"topRight"})}finally{y()}}}async function O(){m(),i(),l++;try{const e=await p(n,l);f(e.hits),document.querySelectorAll(".gallery-item").length>=u?(a.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),i()):h();const t=document.querySelectorAll(".gallery-item");if(t.length>0){const o=(t[t.length-15]||t[0]).getBoundingClientRect().top+window.scrollY;window.scrollTo({top:o,behavior:"smooth"})}}catch(e){a.error({message:e.message,position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
